uuid-runtime: improved user/group handling
- pre-depend on new libuuid1 to make sure no old user handling is present
- add code to rename existing libuuid user/group to uuidd
  and set nologin shell and new home directory.
- switch to adduser instead of opencoding it since uuid-runtime
  is Priority: optional (as opposed to libuuid1 which is required)
  and adduser --system should just do the right thing.
- change user/group addition to add uuidd instead of libuuid.
- stop making uuidd setuid, not needed and we don't want anyone to
  be able to kill the daemon (via uuidd -k) for example.

While at it, drop the obsolete explicit "libuuid1 (>> 1.40.3-1)"
dependency since shlib-deps already pulls in newer.

Git-Dch: Full
Closes: #734544

diff --git a/debian/uuid-runtime.postinst b/debian/uuid-runtime.postinst
--- a/debian/uuid-runtime.postinst
+++ b/debian/uuid-runtime.postinst
@@ -1,15 +1,32 @@
 #!/bin/sh
 
 set -e
-if ! getent group | grep -q libuuid; then
-groupadd -f -K GID_MIN=1 -K GID_MAX=999 libuuid
+
+# upgrade existing libuuid user/group.
+if getent group libuuid >/dev/null && ! getent group uuidd >/dev/null ; then
+	groupmod --new-name uuidd libuuid
 fi
-if ! getent passwd | grep -q libuuid; then
-   useradd -d /var/lib/libuuid -K UID_MIN=1 -K UID_MAX=499 -g libuuid libuuid
+if getent passwd libuuid >/dev/null && ! getent passwd uuidd >/dev/null ; then
+	# switch existing libuuid user to not have a login shell.
+	if [ "$(getent passwd libuuid | cut -d: -f7)" = "/bin/sh" ]; then
+		chsh -s /bin/false libuuid
+	fi
+
+	# rename user and set new homedir.
+	usermod --login uuidd --home /run/uuidd libuuid
+
+	# attemp cleanup of old home directory.
+	rmdir /var/lib/libuuid > /dev/null 2>&1 || true
 fi
-chown libuuid:libuuid /usr/sbin/uuidd
-chmod 6755 /usr/sbin/uuidd
+
+# add uuidd user/group if needed.
+if ! getent group uuidd >/dev/null; then
+	addgroup --system uuidd
+fi
+if ! getent passwd uuidd >/dev/null; then
+	adduser --system --ingroup uuidd \
+		--home /run/uuidd --no-create-home \
+		uuidd
+fi
 
 #DEBHELPER#
-
-exit 0
